### ISSUE TITLE
Class files in repository

### ISSUE THREAD

**Issue by ripleymj** [Pokemaniac00/InterlanguageTest#2]
Sorry to beat up your repo so hard this morning, but I'm bored waiting for my flight to leave, and excited to see you trying out github workflows. Also, this: https://xkcd.com/386/

For your projects, you might want to consider not committing the compiled Java class files to the repository. While git *CAN* handle it, it isn't able to provide any meaningful differencing between versions, and can quickly inflate the size of the repository. Also, for many languages, you're not guaranteed that the binaries will run on the machines checking out the repo, so compiling locally is a safer bet.

As you progress, you might try using Make, Ant, Gradle, Maven, or any other build tool to code the compilation process. That's a big step for now, and you might consider just adding compilation instructions to the README.md, or adding a small shell script to compile your code.

**Comment by Pokemaniac00** [comment]
Thanks for the suggestion! I had realized late last night after uploading the repository that in my shell script file that I could have typed out the compile command and save space with the files in the repository that way, but I will also definitely look at Make, Ant, and other build tools as well! I really appreciate the feedback! 

Thanks again!
